spring:
  application:
    name: pay
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres?useTimezone=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  cache:
    jcache:
      config: classpath:ehcache.xml
  docker:
    compose:
      enabled: true
      file: docker-postgres.yml
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method