spring:
  application:
    name: pay
  datasource:
    url: jdbc:postgresql://localhost:5433/payapi
    username: postgres
    password: "Wallace@08"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  docker:
    compose:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
