CREATE TABLE IF NOT EXISTS SIS_DISCIPLINA(
    CD_DISCIPLINA SERIAL PRIMARY KEY,
    NM_DISCIPLINA VARCHAR(30) NOT NULL,
    CG_HORARIA INTEGER NOT NULL,
    TS_INCLUSAO timestamp  NOT NULL,
    TS_ALTERACAO timestamp
);

COMMENT ON TABLE  SIS_disciplina IS 'TABELA DE REGISTRO DA DISCIPLINA.';
COMMENT ON COLUMN SIS_disciplina.CD_DISCIPLINA IS 'NÚMERO DE IDENTIFICAÇÃO DA DISCIPLINA.';
COMMENT ON COLUMN SIS_disciplina.NM_DISCIPLINA IS 'NOME DA DISCIPLINA.';
COMMENT ON COLUMN SIS_disciplina.CG_HORARIA IS 'CARGA HORARIA DA DISCIPLINA.';
COMMENT ON COLUMN SIS_disciplina.TS_INCLUSAO IS 'DATA DE INCLUSÃO DO REGISTRO';
COMMENT ON COLUMN SIS_disciplina.TS_ALTERACAO IS 'DATA DA ULTIMA ALTERAÇÃO DO REGISTRO.';