CREATE TABLE IF NOT EXISTS SIS_MATERIA(
	CD_MATERIA SERIAL PRIMARY KEY,
	NM_MATERIA VARCHAR(100) NOT NULL UNIQUE,
	CD_DISCIPLINA INTEGER,
	TS_INCLUSAO timestamp  NOT NULL,
    TS_ALTERACAO timestamp,
    CONSTRAINT FK_DISCIPLINA
        FOREIGN KEY(CD_DISCIPLINA)
            REFERENCES SIS_DISCIPLINA(CD_DISCIPLINA)
                ON DELETE SET NULL
	
);

COMMENT ON TABLE SIS_MATERIA IS 'TABELA DE REGISTRO DE MATERIA.';
COMMENT ON COLUMN SIS_MATERIA.CD_MATERIA IS 'NÚMERO DE IDENTIFICAÇÃO DA MATERIA.';
COMMENT ON COLUMN SIS_MATERIA.NM_MATERIA IS 'NOME DA MATERIA.';
COMMENT ON COLUMN SIS_MATERIA.CD_DISCIPLINA IS 'NÚMERO DE IDENTIFICAÇÃO DA DISCIPLINA.';
COMMENT ON COLUMN SIS_MATERIA.TS_INCLUSAO IS 'DATA DE INCLUSÃO DO REGISTRO';
COMMENT ON COLUMN SIS_MATERIA.TS_ALTERACAO IS 'DATA DA ULTIMA ALTERAÇÃO DO REGISTRO.';
