CREATE TABLE IF NOT EXISTS SIS_TURMA(
	CD_TURMA SERIAL PRIMARY KEY,
	AN_ANO INT NOT NULL ,
	SM_SEMESTRE INT NOT NULL,
	TN_TURNO VARCHAR(50) NOT NULL,
	TS_INCLUSAO timestamp  NOT NULL,
    TS_ALTERACAO timestamp
   
);

COMMENT ON TABLE SIS_TURMA IS 'TABELA DE REGISTRO DE TURMA.';
COMMENT ON COLUMN SIS_TURMA.AN_ANO IS 'NÚMERO DE IDENTIFICAÇÃO DA TURMA.';
COMMENT ON COLUMN SIS_TURMA.SM_SEMESTRE IS 'NOME DA TURMA.';
COMMENT ON COLUMN SIS_TURMA.TS_INCLUSAO IS 'DATA DE INCLUSÃO DO REGISTRO';
COMMENT ON COLUMN SIS_TURMA.TS_ALTERACAO IS 'DATA DA ULTIMA ALTERAÇÃO DO REGISTRO.';